### DISCUSSION TITLE
proposed schema for lead scoring

### DISCUSSION THREAD

**Discussion by dduran1967** [Yodata/real-estate#154] [Ideas]
Various systems exist to evaluate and score/rank a lead.
Can we propose a standard basic data model for this activity.

ACTIONS/EVENTS:
- Action by vendor/parter of evaluating a lead and producing a score
- Actions that affect the score over time such as requesting a showing or asking a question on the website
- Action by vendor to produce a updated after an action or some other change happens (note:1)

NOTES:
1. vendor evaluation models are proprietary - might not want to show how a specific action changes the score?

**Comment by dduran1967** [comment]
We have a number of events  defined on the [website](https://realestate.yodata.me/topic/website).

Question: What other actions are relevant for lead scoring?


SUGGESTED ACTIONS PERFORMED BY A LEAD:

1. signs a listing agreement
2. listing close (buyer/seller side)
3. other MLS listing changes (price, status, etc)
4. attends an open house event
5. public records: **divorce**, tax liens, foreclosures, etc...
6. generic actions to lead related events
 
CURRENT ACTIONS:
[askquestion](https://realestate.yodata.me/topic/website#askquestion)
[listingoffer](https://realestate.yodata.me/topic/website#listingoffer)
[register](https://realestate.yodata.me/topic/website#register)
[requestappointment](https://realestate.yodata.me/topic/website#requestappointment)
[requestshowing](https://realestate.yodata.me/topic/website#requestshowing)
[saveproperty](https://realestate.yodata.me/topic/website#saveproperty)
[propertysearchsave](https://realestate.yodata.me/topic/website#propertysearchsave)
[searchproperties](https://realestate.yodata.me/topic/website#searchproperties)
[shareproperty](https://realestate.yodata.me/topic/website#shareproperty)
[sharepropertyvaluereport](https://realestate.yodata.me/topic/website#sharepropertyvaluereport)
[viewproperty](https://realestate.yodata.me/topic/website#viewproperty)
[viewpropertyvaluereort](https://realestate.yodata.me/topic/website#viewpropertyvaluereort)

**Comment by dduran1967** [comment]
### example of a lead score event

```yaml
topic: 'realestate/lead#score'
recipient: 'https://devtest.bhhs.dev.yodata.io/profile/card#me'
data:
  type: AssessAction
  agent:
    type: Organization
    name: Chalk Digital
    url: 'https://www.chalkdigital.com/'
  result:
    type: 'LeadScore (subclass of https://schema.org/Rating)'
    ratingValue: 5
    bestRating: 10
    worstRating: 1
    ratingExplanation: text might be displayed by event consumers to provide a richer UX
  object:
    type: Contact
    identifier:
      contact_producer_id: aaaa
    sameAs:
      leadscoreprovider_id: bbbb
    name: Batman
    email: batman@example.com
```

**Reply by dduran1967** [reply]
posted an example in [examples](https://github.com/Yodata/real-estate/blob/368bd7de940141937cdbdb1ac102a918751bdd41/example/lead/lead%23score.json)

**Reply by dduran1967** [reply]
For consideration:

A model for an updated score for a contact/lead
```yaml
topic: 'realestate/lead#scoreupdate'
recipient: 'https://devtest.bhhs.dev.yodata.io/profile/card#me'
data:
  type: AssessAction
  agent:
    type: Organization
    name: Chalk Digital
    url: 'https://www.chalkdigital.com/'
  result:
    type: 'LeadScore (subclass of https://schema.org/Rating)'
    ratingValue: 5
    bestRating: 10
    worstRating: 1
    ratingExplanation: text might be displayed by event consumers to provide a richer UX
    dateCreated: '2023-12-23T14:14:54.000Z'
    previousRatingValue: 4
    previousRatingDate: '2023-11-01T14:14:54.000Z'
  object:
    type: Contact
    identifier:
      supercrmid: aaa1
```
