### DISCUSSION TITLE
website#shareproperty via social media

### DISCUSSION THREAD

**Discussion by dduran1967** [Yodata/real-estate#165] [Ideas]
We want to modify the schema for website/shareproperty to allow for sharing via social media posting.

The basic outline of the schema is:
type: ShareAction
agent: { the website user who shared the listing }
object: { the listing shared }
participant: { agent or affiliate who's website was used to share the listing }
recipient: { the person who received the shared content }

The only required change to the schema is in the data.recipient

Currently the recipient is a "Person" and the share action only captures the email address.

```yaml
type: string const  Person
email: string<email>
```

For social media posting we'll need to allow for a new type and two properties to capture the event data.

```yaml
type: Audience
name: { if available the name of group or type of share }  @examples [ followers, close friends ]
url:  { link to the post }  @example https://pintrest.com/post/112345
```

The rest of the schema is unchanged.  You can see the details on the website here: https://realestate.yodata.me/docs/topic/website#shareproperty
